export const PROPERTY_REMOVAL_SPIKE_ABSOLUTE_THRESHOLD = 10;

export const PROPERTY_REMOVAL_SPIKE_RATIO_THRESHOLD = 0.3;

export const CRAWL_REMOVAL_COVERAGE_RATIO_THRESHOLD = 0.7;

export const CRAWL_REMOVAL_COVERAGE_MIN_BASELINE = 5;
