import { EstateWebFieldType } from './estateweb-enums.constants';

export interface EstateWebInitFieldOption {
  id: number;
  field_id: number;
  name: string;
}

export interface EstateWebInitField {
  id: number;
  type_id: EstateWebFieldType | number;
  default_value: string | number | null;
  name: string;
  types: number[];
  field_options: EstateWebInitFieldOption[];
}

export interface EstateWebInitPropertyType {
  id: number;
  name: string;
  parent_id: number | null;
  children: EstateWebInitPropertyType[];
}

export const ESTATEWEB_INIT_FIELDS: EstateWebInitField[] = [
  {
    id: 4120,
    type_id: 3,
    default_value: null,
    name: 'Playroom',
    types: [],
    field_options: [],
  },
  {
    id: 4001,
    type_id: 3,
    default_value: null,
    name: 'Roofgarden',
    types: [],
    field_options: [],
  },
  {
    id: 4002,
    type_id: 3,
    default_value: null,
    name: 'W.C.',
    types: [],
    field_options: [],
  },
  {
    id: 2000,
    type_id: 1,
    default_value: null,
    name: 'W.C.',
    types: [21, 22, 23, 24, 25, 26, 27, 28, 29, 1000],
    field_options: [],
  },
  {
    id: 4004,
    type_id: 3,
    default_value: null,
    name: 'Άδεια',
    types: [],
    field_options: [],
  },
  {
    id: 4003,
    type_id: 3,
    default_value: null,
    name: 'Άδεια καταστήματος',
    types: [],
    field_options: [],
  },
  {
    id: 4041,
    type_id: 3,
    default_value: null,
    name: 'Άδεια οικοδομής',
    types: [],
    field_options: [],
  },
  {
    id: 4142,
    type_id: 3,
    default_value: null,
    name: 'Άδεια υγειονομικού ενδιαφέροντος',
    types: [],
    field_options: [],
  },
  {
    id: 1200,
    type_id: 1,
    default_value: null,
    name: 'Αέρας',
    types: [12, 14],
    field_options: [],
  },
  {
    id: 4112,
    type_id: 3,
    default_value: null,
    name: 'Ανακαινισμένο',
    types: [],
    field_options: [],
  },
  {
    id: 4172,
    type_id: 3,
    default_value: null,
    name: 'Ανακαινισμένο μερικώς',
    types: [],
    field_options: [],
  },
  {
    id: 4173,
    type_id: 3,
    default_value: null,
    name: 'Ανακαινισμένο πλήρως',
    types: [],
    field_options: [],
  },
  {
    id: 4005,
    type_id: 3,
    default_value: null,
    name: 'Ανελκυστήρας',
    types: [],
    field_options: [],
  },
  {
    id: 4075,
    type_id: 3,
    default_value: null,
    name: 'Ανελκυστήρας επαγγελμ.',
    types: [],
    field_options: [],
  },
  {
    id: 4006,
    type_id: 3,
    default_value: null,
    name: 'Αποθήκη',
    types: [],
    field_options: [],
  },
  {
    id: 4007,
    type_id: 3,
    default_value: null,
    name: 'Αποχέτευση',
    types: [],
    field_options: [],
  },
  {
    id: 3100,
    type_id: 1,
    default_value: null,
    name: 'Αρ. Bangalows',
    types: [31, 32],
    field_options: [],
  },
  {
    id: 3028,
    type_id: 1,
    default_value: null,
    name: 'Αρ. αποθηκών',
    types: [28, 31, 32, 33],
    field_options: [],
  },
  {
    id: 2817,
    type_id: 1,
    default_value: null,
    name: 'Αρ. αποθηκών (σύνολο)',
    types: [28],
    field_options: [],
  },
  {
    id: 4164,
    type_id: 3,
    default_value: null,
    name: 'Άρδευση από γεώτρηση',
    types: [],
    field_options: [],
  },
  {
    id: 4162,
    type_id: 3,
    default_value: null,
    name: 'Άρδευση από δεξαμενή',
    types: [],
    field_options: [],
  },
  {
    id: 4165,
    type_id: 3,
    default_value: null,
    name: 'Άρδευση από πηγάδι',
    types: [],
    field_options: [],
  },
  {
    id: 4161,
    type_id: 3,
    default_value: null,
    name: 'Άρδευση από ΤΟΕΒ',
    types: [],
    field_options: [],
  },
  {
    id: 4163,
    type_id: 3,
    default_value: null,
    name: 'Άρδευση από χαβούζα',
    types: [],
    field_options: [],
  },
  {
    id: 4127,
    type_id: 3,
    default_value: null,
    name: 'Αρδεύσιμο',
    types: [],
    field_options: [],
  },
  {
    id: 3012,
    type_id: 1,
    default_value: null,
    name: 'Αρ. διαμερισμάτων (σύνολο)',
    types: [31, 32, 33],
    field_options: [],
  },
  {
    id: 3017,
    type_id: 1,
    default_value: null,
    name: 'Αρ. δίχωρων',
    types: [31, 32, 33],
    field_options: [],
  },
  {
    id: 3013,
    type_id: 1,
    default_value: null,
    name: 'Αρ. δωματίων (σύνολο',
    types: [31, 32, 33],
    field_options: [],
  },
  {
    id: 2803,
    type_id: 1,
    default_value: null,
    name: 'Αρ. καταστημάτων (σύνολο)',
    types: [28, 31, 32, 33],
    field_options: [],
  },
  {
    id: 3002,
    type_id: 1,
    default_value: null,
    name: 'Αρ. κλινών (σύνολο)',
    types: [31, 32, 33],
    field_options: [],
  },
  {
    id: 3020,
    type_id: 1,
    default_value: null,
    name: 'Αρ. μεζονετών',
    types: [31, 32, 33],
    field_options: [],
  },
  {
    id: 2820,
    type_id: 1,
    default_value: null,
    name: 'Αρ. μονοκατοικιών',
    types: [28, 32],
    field_options: [],
  },
  {
    id: 3016,
    type_id: 1,
    default_value: null,
    name: 'Αρ. μονόχωρων',
    types: [31, 32, 33],
    field_options: [],
  },
  {
    id: 1302,
    type_id: 1,
    default_value: null,
    name: 'Αρ. ορόφων (σύνολο)',
    types: [13],
    field_options: [],
  },
  {
    id: 2801,
    type_id: 1,
    default_value: null,
    name: 'Αρ. σπιτιών (σύνολο)',
    types: [28],
    field_options: [],
  },
  {
    id: 3019,
    type_id: 1,
    default_value: null,
    name: 'Αρ. τετράχωρων',
    types: [31, 32, 33],
    field_options: [],
  },
  {
    id: 4193,
    type_id: 3,
    default_value: null,
    name: 'Άρτιο',
    types: [],
    field_options: [],
  },
  {
    id: 3018,
    type_id: 1,
    default_value: null,
    name: 'Αρ. τρίχωρων',
    types: [31, 32, 33],
    field_options: [],
  },
  {
    id: 3000,
    type_id: 4,
    default_value: null,
    name: 'Αστέρων',
    types: [31, 32, 33],
    field_options: [],
  },
  {
    id: 4143,
    type_id: 3,
    default_value: null,
    name: 'Αύλειος χώρος',
    types: [],
    field_options: [],
  },
  {
    id: 4008,
    type_id: 3,
    default_value: null,
    name: 'Αυλή',
    types: [],
    field_options: [],
  },
  {
    id: 4009,
    type_id: 3,
    default_value: null,
    name: 'Αυτόνομη θέρμανση',
    types: [],
    field_options: [],
  },
  {
    id: 4111,
    type_id: 3,
    default_value: null,
    name: 'Βαμμένο πρόσφατα',
    types: [],
    field_options: [],
  },
  {
    id: 4010,
    type_id: 3,
    default_value: null,
    name: 'Βεράντα',
    types: [],
    field_options: [],
  },
  {
    id: 4012,
    type_id: 3,
    default_value: null,
    name: 'Βοηθητικό δωμάτιο',
    types: [],
    field_options: [],
  },
  {
    id: 4013,
    type_id: 3,
    default_value: null,
    name: 'Βόθρος',
    types: [],
    field_options: [],
  },
  {
    id: 4147,
    type_id: 3,
    default_value: null,
    name: 'Βραχυπρόθεσμη μίσθωση',
    types: [],
    field_options: [],
  },
  {
    id: 4073,
    type_id: 3,
    default_value: null,
    name: 'Γεώτρηση',
    types: [],
    field_options: [],
  },
  {
    id: 4154,
    type_id: 3,
    default_value: null,
    name: 'Γήπεδο Τένις',
    types: [],
    field_options: [],
  },
  {
    id: 4077,
    type_id: 3,
    default_value: null,
    name: 'Γκαζόν',
    types: [],
    field_options: [],
  },
  {
    id: 2812,
    type_id: 1,
    default_value: null,
    name: 'Γκαρσονιέρες (σύνολο)',
    types: [28],
    field_options: [],
  },
  {
    id: 4014,
    type_id: 3,
    default_value: null,
    name: 'Γυμναστήριο',
    types: [],
    field_options: [],
  },
  {
    id: 4015,
    type_id: 3,
    default_value: null,
    name: 'Γωνιακό',
    types: [],
    field_options: [],
  },
  {
    id: 4192,
    type_id: 3,
    default_value: null,
    name: 'Δεν επιτρέπονται κατοικίδια',
    types: [],
    field_options: [],
  },
  {
    id: 4016,
    type_id: 3,
    default_value: null,
    name: 'Δεντροφυτεμένο',
    types: [],
    field_options: [],
  },
  {
    id: 4017,
    type_id: 3,
    default_value: null,
    name: 'Δεξαμενή νερού',
    types: [],
    field_options: [],
  },
  {
    id: 4090,
    type_id: 3,
    default_value: null,
    name: 'Διαμπερές',
    types: [],
    field_options: [],
  },
  {
    id: 4184,
    type_id: 3,
    default_value: null,
    name: 'Διατήρηση οροφής',
    types: [],
    field_options: [],
  },
  {
    id: 4183,
    type_id: 3,
    default_value: null,
    name: 'Διατήρηση τοίχων',
    types: [],
    field_options: [],
  },
  {
    id: 4137,
    type_id: 3,
    default_value: null,
    name: 'Διατηρητέο',
    types: [],
    field_options: [],
  },
  {
    id: 4114,
    type_id: 3,
    default_value: null,
    name: 'Διπλά τζάμια',
    types: [],
    field_options: [],
  },
  {
    id: 4151,
    type_id: 3,
    default_value: null,
    name: 'Δομημένη καλωδίωση',
    types: [],
    field_options: [],
  },
  {
    id: 4084,
    type_id: 3,
    default_value: null,
    name: 'Δορυφορική κεραία',
    types: [],
    field_options: [],
  },
  {
    id: 110,
    type_id: 2,
    default_value: null,
    name: 'Δρόμος',
    types: [2, 3, 21, 22, 23, 24, 25, 26, 27, 28, 29, 1000],
    field_options: [
      {
        id: 15,
        field_id: 110,
        name: 'Όχι',
      },
      {
        id: 16,
        field_id: 110,
        name: 'Άσφαλτος',
      },
      {
        id: 19,
        field_id: 110,
        name: 'Χωματόδρομος',
      },
      {
        id: 20,
        field_id: 110,
        name: 'Τσιμεντένιος',
      },
      {
        id: 17,
        field_id: 110,
        name: 'Πεζόδρομος',
      },
      {
        id: 18,
        field_id: 110,
        name: 'Πλακόστρωτο',
      },
    ],
  },
  {
    id: 2813,
    type_id: 1,
    default_value: null,
    name: 'Δυάρια (σύνολο)',
    types: [28],
    field_options: [],
  },
  {
    id: 4160,
    type_id: 3,
    default_value: null,
    name: 'Δυνατότητα άρδευσης',
    types: [],
    field_options: [],
  },
  {
    id: 4108,
    type_id: 3,
    default_value: null,
    name: 'Δώμα',
    types: [],
    field_options: [],
  },
  {
    id: 4185,
    type_id: 2,
    default_value: null,
    name: 'Είδος γκαρσονιέρας',
    types: [21],
    field_options: [
      {
        id: 40,
        field_id: 4185,
        name: 'Δώμα',
      },
      {
        id: 41,
        field_id: 4185,
        name: 'Μονόχωρη',
      },
      {
        id: 42,
        field_id: 4185,
        name: 'Δίχωρη',
      },
      {
        id: 43,
        field_id: 4185,
        name: 'Studio',
      },
      {
        id: 44,
        field_id: 4185,
        name: 'Ρετιρέ',
      },
    ],
  },
  {
    id: 108,
    type_id: 2,
    default_value: null,
    name: 'Είδος εδάφους',
    types: [2, 3],
    field_options: [
      {
        id: 1,
        field_id: 108,
        name: 'Εύφορο',
      },
      {
        id: 2,
        field_id: 108,
        name: 'Βραχώδες',
      },
    ],
  },
  {
    id: 4186,
    type_id: 2,
    default_value: null,
    name: 'Είδος εξοχικού',
    types: [1000],
    field_options: [
      {
        id: 50,
        field_id: 4186,
        name: 'Studio',
      },
      {
        id: 51,
        field_id: 4186,
        name: 'Δώμα',
      },
      {
        id: 52,
        field_id: 4186,
        name: 'Διαμέρισμα',
      },
      {
        id: 53,
        field_id: 4186,
        name: 'Οροφοδιαμέρισμα',
      },
      {
        id: 54,
        field_id: 4186,
        name: 'Μονόχωρο',
      },
      {
        id: 55,
        field_id: 4186,
        name: 'Δίχωρo',
      },
      {
        id: 56,
        field_id: 4186,
        name: 'Μεζονέτα',
      },
      {
        id: 57,
        field_id: 4186,
        name: 'Ρετιρέ',
      },
    ],
  },
  {
    id: 4145,
    type_id: 3,
    default_value: null,
    name: 'Εκτός οικισμού',
    types: [],
    field_options: [],
  },
  {
    id: 4146,
    type_id: 3,
    default_value: null,
    name: 'Εκτός σχεδίου',
    types: [],
    field_options: [],
  },
  {
    id: 4129,
    type_id: 3,
    default_value: null,
    name: 'Ελαιώνας',
    types: [],
    field_options: [],
  },
  {
    id: 4171,
    type_id: 3,
    default_value: null,
    name: 'Εμπόδια τεχνητά',
    types: [],
    field_options: [],
  },
  {
    id: 4170,
    type_id: 3,
    default_value: null,
    name: 'Εμπόδια φυσικά',
    types: [],
    field_options: [],
  },
  {
    id: 4116,
    type_id: 3,
    default_value: null,
    name: 'Ενδοδαπέδια θέρμανση',
    types: [],
    field_options: [],
  },
  {
    id: 2010,
    type_id: 2,
    default_value: null,
    name: 'Ενεργειακή κλάση',
    types: [
      21, 22, 23, 24, 25, 26, 27, 28, 29, 11, 12, 13, 14, 15, 16, 17, 31, 32,
      33, 1000,
    ],
    field_options: [
      {
        id: 24,
        field_id: 2010,
        name: 'Α+',
      },
      {
        id: 25,
        field_id: 2010,
        name: 'Α',
      },
      {
        id: 26,
        field_id: 2010,
        name: 'Β+',
      },
      {
        id: 27,
        field_id: 2010,
        name: 'Β',
      },
      {
        id: 28,
        field_id: 2010,
        name: 'Γ',
      },
      {
        id: 29,
        field_id: 2010,
        name: 'Δ',
      },
      {
        id: 30,
        field_id: 2010,
        name: 'Ε',
      },
      {
        id: 31,
        field_id: 2010,
        name: 'Ζ',
      },
      {
        id: 32,
        field_id: 2010,
        name: 'Η',
      },
      {
        id: 33,
        field_id: 2010,
        name: 'Δεν απαιτείται',
      },
      {
        id: 34,
        field_id: 2010,
        name: 'Έκδοση σε εξέλιξη',
      },
    ],
  },
  {
    id: 4018,
    type_id: 3,
    default_value: null,
    name: 'Ενιαίος χώρος',
    types: [],
    field_options: [],
  },
  {
    id: 4123,
    type_id: 3,
    default_value: null,
    name: 'Εντοιχισμένες ντουλάπες',
    types: [],
    field_options: [],
  },
  {
    id: 4019,
    type_id: 3,
    default_value: null,
    name: 'Εντός οικισμού',
    types: [],
    field_options: [],
  },
  {
    id: 4020,
    type_id: 3,
    default_value: null,
    name: 'Εντός σχεδίου',
    types: [],
    field_options: [],
  },
  {
    id: 4125,
    type_id: 3,
    default_value: null,
    name: 'Εξοπλισμένο',
    types: [],
    field_options: [],
  },
  {
    id: 4091,
    type_id: 3,
    default_value: null,
    name: 'Έπαυλης',
    types: [],
    field_options: [],
  },
  {
    id: 4148,
    type_id: 3,
    default_value: null,
    name: 'Επενδυτικό ακίνητο',
    types: [],
    field_options: [],
  },
  {
    id: 4189,
    type_id: 2,
    default_value: null,
    name: 'Επίπεδο',
    types: [902],
    field_options: [
      {
        id: 130,
        field_id: 4189,
        name: 'Ισόγειο',
      },
      {
        id: 131,
        field_id: 4189,
        name: 'Υπόγειο',
      },
      {
        id: 132,
        field_id: 4189,
        name: '1',
      },
      {
        id: 133,
        field_id: 4189,
        name: '2',
      },
      {
        id: 134,
        field_id: 4189,
        name: '3',
      },
      {
        id: 135,
        field_id: 4189,
        name: '4',
      },
      {
        id: 136,
        field_id: 4189,
        name: '-2',
      },
      {
        id: 137,
        field_id: 4189,
        name: '-3',
      },
      {
        id: 138,
        field_id: 4189,
        name: '-4',
      },
    ],
  },
  {
    id: 4022,
    type_id: 3,
    default_value: null,
    name: 'Επιπλωμένο',
    types: [],
    field_options: [],
  },
  {
    id: 4023,
    type_id: 3,
    default_value: null,
    name: 'Επιτρέπονται ζώα',
    types: [],
    field_options: [],
  },
  {
    id: 4136,
    type_id: 3,
    default_value: null,
    name: 'Επιτρέπονται κατοικίδια',
    types: [],
    field_options: [],
  },
  {
    id: 4024,
    type_id: 3,
    default_value: null,
    name: 'Εστιατόριο',
    types: [],
    field_options: [],
  },
  {
    id: 4085,
    type_id: 3,
    default_value: null,
    name: 'Εσωτερική σκάλα',
    types: [],
    field_options: [],
  },
  {
    id: 1014,
    type_id: 4,
    default_value: null,
    name: 'Έτος ανακαίνισης',
    types: [
      11, 12, 13, 14, 15, 16, 17, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32,
      33, 1000,
    ],
    field_options: [],
  },
  {
    id: 1013,
    type_id: 4,
    default_value: null,
    name: 'Έτος κατασκευής',
    types: [
      11, 12, 13, 14, 15, 16, 17, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32,
      33, 1000,
    ],
    field_options: [],
  },
  {
    id: 4025,
    type_id: 3,
    default_value: null,
    name: 'Ηλεκτρικές συσκευές',
    types: [],
    field_options: [],
  },
  {
    id: 4102,
    type_id: 3,
    default_value: null,
    name: 'Ηλεκτρική γκαραζόπορτα',
    types: [],
    field_options: [],
  },
  {
    id: 4027,
    type_id: 3,
    default_value: null,
    name: 'Ηλεκτρικός θερμοσ.',
    types: [],
    field_options: [],
  },
  {
    id: 4028,
    type_id: 3,
    default_value: null,
    name: 'Ηλιακός θερμοσ.',
    types: [],
    field_options: [],
  },
  {
    id: 4029,
    type_id: 3,
    default_value: null,
    name: 'Ημιτελές',
    types: [],
    field_options: [],
  },
  {
    id: 4092,
    type_id: 3,
    default_value: null,
    name: 'Ημιυπόγειο',
    types: [],
    field_options: [],
  },
  {
    id: 4030,
    type_id: 3,
    default_value: null,
    name: 'Θέα',
    types: [],
    field_options: [],
  },
  {
    id: 4128,
    type_id: 3,
    default_value: null,
    name: 'Θερμοκήπιο',
    types: [],
    field_options: [],
  },
  {
    id: 4032,
    type_id: 3,
    default_value: null,
    name: 'Θερμοσυσσωρευτές',
    types: [],
    field_options: [],
  },
  {
    id: 4190,
    type_id: 4,
    default_value: null,
    name: 'Θέσεις',
    types: [902],
    field_options: [],
  },
  {
    id: 1012,
    type_id: 1,
    default_value: null,
    name: 'Θέσεις στάθμευσης',
    types: [
      11, 12, 13, 14, 15, 16, 17, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32,
      33, 901, 1000,
    ],
    field_options: [],
  },
  {
    id: 4074,
    type_id: 3,
    default_value: null,
    name: 'Θυροτηλεόραση',
    types: [],
    field_options: [],
  },
  {
    id: 4094,
    type_id: 3,
    default_value: null,
    name: 'Ισόγειο',
    types: [],
    field_options: [],
  },
  {
    id: 4140,
    type_id: 3,
    default_value: null,
    name: 'Καλοκαιρινή μίσθωση',
    types: [],
    field_options: [],
  },
  {
    id: 4134,
    type_id: 3,
    default_value: null,
    name: 'Καλωδιακή τηλεόραση',
    types: [],
    field_options: [],
  },
  {
    id: 4139,
    type_id: 3,
    default_value: null,
    name: 'Κατάλληλο για αγροτική χρήση',
    types: [],
    field_options: [],
  },
  {
    id: 4118,
    type_id: 3,
    default_value: null,
    name: 'Κατάλληλο για εξοχικό',
    types: [],
    field_options: [],
  },
  {
    id: 4119,
    type_id: 3,
    default_value: null,
    name: 'Κατάλληλο για επαγγελματική χρήση',
    types: [],
    field_options: [],
  },
  {
    id: 4130,
    type_id: 3,
    default_value: null,
    name: 'Κατάλληλο για φοιτητές',
    types: [],
    field_options: [],
  },
  {
    id: 2910,
    type_id: 1,
    default_value: null,
    name: 'Κατάσταση των γειτονικών',
    types: [29],
    field_options: [],
  },
  {
    id: 3011,
    type_id: 1,
    default_value: null,
    name: 'Κατηγορία',
    types: [31, 32, 33],
    field_options: [],
  },
  {
    id: 4174,
    type_id: 3,
    default_value: null,
    name: 'Κατοικήσιμο',
    types: [],
    field_options: [],
  },
  {
    id: 4034,
    type_id: 3,
    default_value: null,
    name: 'Καφετέρια',
    types: [],
    field_options: [],
  },
  {
    id: 4035,
    type_id: 3,
    default_value: null,
    name: 'Κεντρική θέρμανση',
    types: [],
    field_options: [],
  },
  {
    id: 4036,
    type_id: 3,
    default_value: null,
    name: 'Κεντρικό',
    types: [],
    field_options: [],
  },
  {
    id: 4037,
    type_id: 3,
    default_value: null,
    name: 'Κήπος',
    types: [],
    field_options: [],
  },
  {
    id: 4038,
    type_id: 3,
    default_value: null,
    name: 'Κλειστό πάρκινγκ',
    types: [],
    field_options: [],
  },
  {
    id: 4039,
    type_id: 3,
    default_value: null,
    name: 'Κλιματισμός',
    types: [],
    field_options: [],
  },
  {
    id: 111,
    type_id: 2,
    default_value: null,
    name: 'Κλίση εδάφους',
    types: [2, 3],
    field_options: [
      {
        id: 21,
        field_id: 111,
        name: 'Επίπεδο',
      },
      {
        id: 22,
        field_id: 111,
        name: 'Επικλινές',
      },
      {
        id: 23,
        field_id: 111,
        name: 'Αμφιθεατρικό',
      },
    ],
  },
  {
    id: 1001,
    type_id: 1,
    default_value: null,
    name: 'Κοινόχρηστα €/μήνα',
    types: [
      11, 12, 13, 14, 15, 16, 17, 21, 22, 23, 24, 25, 26, 27, 28, 29, 1000,
    ],
    field_options: [],
  },
  {
    id: 4104,
    type_id: 3,
    default_value: null,
    name: 'Κοντά σε super market',
    types: [],
    field_options: [],
  },
  {
    id: 4106,
    type_id: 3,
    default_value: null,
    name: 'Κοντά σε εκκλησία',
    types: [],
    field_options: [],
  },
  {
    id: 4105,
    type_id: 3,
    default_value: null,
    name: 'Κοντά σε παραλία',
    types: [],
    field_options: [],
  },
  {
    id: 4107,
    type_id: 3,
    default_value: null,
    name: 'Κοντά σε πάρκινγκ',
    types: [],
    field_options: [],
  },
  {
    id: 4153,
    type_id: 3,
    default_value: null,
    name: 'Κοντά σε στάση λεωφ.',
    types: [],
    field_options: [],
  },
  {
    id: 4103,
    type_id: 3,
    default_value: null,
    name: 'Κοντά σε σχολείο',
    types: [],
    field_options: [],
  },
  {
    id: 4093,
    type_id: 3,
    default_value: null,
    name: 'Κουφώματα PVC',
    types: [],
    field_options: [],
  },
  {
    id: 4040,
    type_id: 3,
    default_value: null,
    name: 'Κουφώματα αλουμινίου',
    types: [],
    field_options: [],
  },
  {
    id: 4083,
    type_id: 3,
    default_value: null,
    name: 'Κουφώματα ξύλινα',
    types: [],
    field_options: [],
  },
  {
    id: 4177,
    type_id: 3,
    default_value: null,
    name: 'Κτισμένο με πέτρες',
    types: [],
    field_options: [],
  },
  {
    id: 4179,
    type_id: 3,
    default_value: null,
    name: 'Κτισμένο με πυλό',
    types: [],
    field_options: [],
  },
  {
    id: 4178,
    type_id: 3,
    default_value: null,
    name: 'Κτισμένο με τούβλα',
    types: [],
    field_options: [],
  },
  {
    id: 2816,
    type_id: 1,
    default_value: null,
    name: 'Μεζονέτες (σύνολο)',
    types: [28],
    field_options: [],
  },
  {
    id: 4159,
    type_id: 3,
    default_value: null,
    name: 'Μη αρδευόμενο',
    types: [],
    field_options: [],
  },
  {
    id: 4175,
    type_id: 3,
    default_value: null,
    name: 'Μη κατοικήσιμο',
    types: [],
    field_options: [],
  },
  {
    id: 4043,
    type_id: 3,
    default_value: null,
    name: 'Μόνωση',
    types: [],
    field_options: [],
  },
  {
    id: 2003,
    type_id: 1,
    default_value: null,
    name: 'Μπαλκόνια',
    types: [21, 22, 23, 24, 25, 26, 27, 28, 29, 1000, 13],
    field_options: [],
  },
  {
    id: 2004,
    type_id: 1,
    default_value: null,
    name: 'Μπάνια',
    types: [21, 22, 23, 24, 25, 26, 27, 28, 29, 1000],
    field_options: [],
  },
  {
    id: 4044,
    type_id: 3,
    default_value: null,
    name: 'Μπαρ',
    types: [],
    field_options: [],
  },
  {
    id: 4045,
    type_id: 3,
    default_value: null,
    name: 'Μπάρμπεκιου',
    types: [],
    field_options: [],
  },
  {
    id: 4132,
    type_id: 3,
    default_value: null,
    name: 'Νεόδμητο',
    types: [],
    field_options: [],
  },
  {
    id: 4138,
    type_id: 3,
    default_value: null,
    name: 'Νεοκλασσικό',
    types: [],
    field_options: [],
  },
  {
    id: 2005,
    type_id: 1,
    default_value: null,
    name: 'Ντουλάπες',
    types: [21, 22, 23, 24, 25, 26, 27, 28, 29, 1000],
    field_options: [],
  },
  {
    id: 4080,
    type_id: 3,
    default_value: null,
    name: 'Ξενώνας',
    types: [],
    field_options: [],
  },
  {
    id: 4141,
    type_id: 3,
    default_value: null,
    name: 'Οικιστικό',
    types: [],
    field_options: [],
  },
  {
    id: 4047,
    type_id: 3,
    default_value: null,
    name: 'Οικοδομήσιμο',
    types: [],
    field_options: [],
  },
  {
    id: 2600,
    type_id: 1,
    default_value: null,
    name: 'Οικόπεδο (τ.μ.)',
    types: [26, 27],
    field_options: [],
  },
  {
    id: 4180,
    type_id: 3,
    default_value: null,
    name: 'Οροφή με δοκάρια',
    types: [],
    field_options: [],
  },
  {
    id: 4182,
    type_id: 3,
    default_value: null,
    name: 'Οροφή με κεραμίδια',
    types: [],
    field_options: [],
  },
  {
    id: 4181,
    type_id: 3,
    default_value: null,
    name: 'Οροφή με ταράτσα',
    types: [],
    field_options: [],
  },
  {
    id: 4144,
    type_id: 3,
    default_value: null,
    name: 'Οροφοδιαμέρισμα',
    types: [],
    field_options: [],
  },
  {
    id: 1202,
    type_id: 1,
    default_value: null,
    name: 'Όροφοι',
    types: [12, 15, 26, 27, 28, 31, 32, 33],
    field_options: [],
  },
  {
    id: 4191,
    type_id: 4,
    default_value: null,
    name: 'Όροφοι / Επίπεδα',
    types: [12, 15, 26, 27, 28, 29, 1000, 31, 32, 33],
    field_options: [],
  },
  {
    id: 4187,
    type_id: 2,
    default_value: null,
    name: 'Όροφος',
    types: [13, 21, 22, 23, 24, 25, 26],
    field_options: [
      {
        id: 60,
        field_id: 4187,
        name: 'Υπόγειο',
      },
      {
        id: 61,
        field_id: 4187,
        name: 'Ημιυπόγειο',
      },
      {
        id: 62,
        field_id: 4187,
        name: 'Ισόγειο',
      },
      {
        id: 63,
        field_id: 4187,
        name: 'Ισόγειο υπερυψωμένο',
      },
      {
        id: 64,
        field_id: 4187,
        name: 'Ημιόροφος',
      },
      {
        id: 65,
        field_id: 4187,
        name: '1',
      },
      {
        id: 66,
        field_id: 4187,
        name: '2',
      },
      {
        id: 67,
        field_id: 4187,
        name: '3',
      },
      {
        id: 68,
        field_id: 4187,
        name: '4',
      },
      {
        id: 69,
        field_id: 4187,
        name: '5',
      },
      {
        id: 70,
        field_id: 4187,
        name: '6',
      },
      {
        id: 71,
        field_id: 4187,
        name: '7',
      },
      {
        id: 72,
        field_id: 4187,
        name: '8',
      },
      {
        id: 73,
        field_id: 4187,
        name: '9',
      },
      {
        id: 74,
        field_id: 4187,
        name: '10',
      },
      {
        id: 75,
        field_id: 4187,
        name: '11',
      },
      {
        id: 76,
        field_id: 4187,
        name: '12',
      },
      {
        id: 77,
        field_id: 4187,
        name: '13',
      },
      {
        id: 78,
        field_id: 4187,
        name: '14',
      },
      {
        id: 79,
        field_id: 4187,
        name: '15',
      },
      {
        id: 80,
        field_id: 4187,
        name: '16',
      },
      {
        id: 81,
        field_id: 4187,
        name: '17',
      },
      {
        id: 82,
        field_id: 4187,
        name: '18',
      },
      {
        id: 83,
        field_id: 4187,
        name: '19',
      },
      {
        id: 84,
        field_id: 4187,
        name: '20',
      },
      {
        id: 85,
        field_id: 4187,
        name: '21',
      },
      {
        id: 86,
        field_id: 4187,
        name: '22',
      },
      {
        id: 87,
        field_id: 4187,
        name: '23',
      },
      {
        id: 88,
        field_id: 4187,
        name: '24',
      },
      {
        id: 89,
        field_id: 4187,
        name: '25',
      },
      {
        id: 90,
        field_id: 4187,
        name: '26',
      },
      {
        id: 91,
        field_id: 4187,
        name: '27',
      },
      {
        id: 92,
        field_id: 4187,
        name: '28',
      },
      {
        id: 93,
        field_id: 4187,
        name: '29',
      },
      {
        id: 94,
        field_id: 4187,
        name: '30',
      },
      {
        id: 95,
        field_id: 4187,
        name: '31',
      },
      {
        id: 96,
        field_id: 4187,
        name: '32',
      },
      {
        id: 97,
        field_id: 4187,
        name: '33',
      },
      {
        id: 98,
        field_id: 4187,
        name: '34',
      },
      {
        id: 99,
        field_id: 4187,
        name: '35',
      },
      {
        id: 100,
        field_id: 4187,
        name: '36',
      },
      {
        id: 101,
        field_id: 4187,
        name: '37',
      },
      {
        id: 102,
        field_id: 4187,
        name: '38',
      },
      {
        id: 103,
        field_id: 4187,
        name: '39',
      },
      {
        id: 104,
        field_id: 4187,
        name: '40',
      },
      {
        id: 105,
        field_id: 4187,
        name: '41',
      },
      {
        id: 106,
        field_id: 4187,
        name: '42',
      },
      {
        id: 107,
        field_id: 4187,
        name: '43',
      },
      {
        id: 108,
        field_id: 4187,
        name: '44',
      },
      {
        id: 109,
        field_id: 4187,
        name: '45',
      },
      {
        id: 110,
        field_id: 4187,
        name: '46',
      },
      {
        id: 111,
        field_id: 4187,
        name: '47',
      },
      {
        id: 112,
        field_id: 4187,
        name: '48',
      },
      {
        id: 113,
        field_id: 4187,
        name: '49',
      },
      {
        id: 114,
        field_id: 4187,
        name: '50',
      },
    ],
  },
  {
    id: 1300,
    type_id: 1,
    default_value: null,
    name: 'Όροφος (συμπλ.)',
    types: [13, 21, 22, 23, 24, 25],
    field_options: [],
  },
  {
    id: 4078,
    type_id: 3,
    default_value: null,
    name: 'Παιδική χαρά',
    types: [],
    field_options: [],
  },
  {
    id: 103,
    type_id: 1,
    default_value: null,
    name: 'Παράδοση την',
    types: [
      2, 3, 11, 12, 13, 14, 15, 16, 17, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31,
      32, 33, 901, 902, 17, 1000,
    ],
    field_options: [],
  },
  {
    id: 4048,
    type_id: 3,
    default_value: null,
    name: 'Παραθαλάσσιο',
    types: [],
    field_options: [],
  },
  {
    id: 4049,
    type_id: 3,
    default_value: null,
    name: 'Πάρκινγκ',
    types: [],
    field_options: [],
  },
  {
    id: 4087,
    type_id: 3,
    default_value: null,
    name: 'Πάρκινγκ υπογείου',
    types: [],
    field_options: [],
  },
  {
    id: 4050,
    type_id: 3,
    default_value: null,
    name: 'Πατάρι',
    types: [],
    field_options: [],
  },
  {
    id: 4101,
    type_id: 3,
    default_value: null,
    name: 'Πάτωμα laminate',
    types: [],
    field_options: [],
  },
  {
    id: 4011,
    type_id: 3,
    default_value: null,
    name: 'Πάτωμα βιομηχανικό',
    types: [],
    field_options: [],
  },
  {
    id: 4051,
    type_id: 3,
    default_value: null,
    name: 'Πάτωμα γρανίτης',
    types: [],
    field_options: [],
  },
  {
    id: 4052,
    type_id: 3,
    default_value: null,
    name: 'Πάτωμα μάρμαρο',
    types: [],
    field_options: [],
  },
  {
    id: 4053,
    type_id: 3,
    default_value: null,
    name: 'Πάτωμα μωσαϊκό',
    types: [],
    field_options: [],
  },
  {
    id: 4054,
    type_id: 3,
    default_value: null,
    name: 'Πάτωμα ξύλο',
    types: [],
    field_options: [],
  },
  {
    id: 4055,
    type_id: 3,
    default_value: null,
    name: 'Πάτωμα πλακάκι',
    types: [],
    field_options: [],
  },
  {
    id: 4056,
    type_id: 3,
    default_value: null,
    name: 'Πάτωμα τσιμέντο',
    types: [],
    field_options: [],
  },
  {
    id: 4121,
    type_id: 3,
    default_value: null,
    name: 'Πέργκολα',
    types: [],
    field_options: [],
  },
  {
    id: 4057,
    type_id: 3,
    default_value: null,
    name: 'Περιφραγμένο',
    types: [],
    field_options: [],
  },
  {
    id: 4095,
    type_id: 3,
    default_value: null,
    name: 'Πετρέλαιο',
    types: [],
    field_options: [],
  },
  {
    id: 4076,
    type_id: 3,
    default_value: null,
    name: 'Πιλοτή',
    types: [],
    field_options: [],
  },
  {
    id: 4058,
    type_id: 3,
    default_value: null,
    name: 'Πισίνα',
    types: [],
    field_options: [],
  },
  {
    id: 4109,
    type_id: 3,
    default_value: null,
    name: 'Πιστοποιητικό νομιμότητας',
    types: [],
    field_options: [],
  },
  {
    id: 104,
    type_id: 1,
    default_value: null,
    name: 'Πλήθος ιδιοκτητών',
    types: [2, 3],
    field_options: [],
  },
  {
    id: 4157,
    type_id: 3,
    default_value: null,
    name: 'Πλυντήριο',
    types: [],
    field_options: [],
  },
  {
    id: 4155,
    type_id: 3,
    default_value: null,
    name: 'Πλυντήριο πιάτων',
    types: [],
    field_options: [],
  },
  {
    id: 4131,
    type_id: 3,
    default_value: null,
    name: 'Πολυτελής κατοικία',
    types: [],
    field_options: [],
  },
  {
    id: 4086,
    type_id: 3,
    default_value: null,
    name: 'Πόρτα ασφαλείας',
    types: [],
    field_options: [],
  },
  {
    id: 300,
    type_id: 1,
    default_value: null,
    name: 'Ποσοστό κάλυψης (%)',
    types: [3, 29],
    field_options: [],
  },
  {
    id: 4059,
    type_id: 3,
    default_value: null,
    name: 'Πρασιά',
    types: [],
    field_options: [],
  },
  {
    id: 4060,
    type_id: 3,
    default_value: null,
    name: 'Προβολή',
    types: [],
    field_options: [],
  },
  {
    id: 109,
    type_id: 2,
    default_value: null,
    name: 'Προσανατολισμός',
    types: [2, 3],
    field_options: [
      {
        id: 3,
        field_id: 109,
        name: 'Ανατολικός',
      },
      {
        id: 4,
        field_id: 109,
        name: 'Ανατολικοδυτικός',
      },
      {
        id: 5,
        field_id: 109,
        name: 'Ανατολικομεσημβρινός',
      },
      {
        id: 6,
        field_id: 109,
        name: 'Βόρειος',
      },
      {
        id: 7,
        field_id: 109,
        name: 'Βορειανατολικός',
      },
      {
        id: 8,
        field_id: 109,
        name: 'Βορειοδυτικός',
      },
      {
        id: 9,
        field_id: 109,
        name: 'Δυτικός',
      },
      {
        id: 10,
        field_id: 109,
        name: 'Δυτικομεσημβρινός',
      },
      {
        id: 11,
        field_id: 109,
        name: 'Μεσημβρινός',
      },
      {
        id: 12,
        field_id: 109,
        name: 'Νότιος',
      },
      {
        id: 13,
        field_id: 109,
        name: 'Νοτιοανατολικός',
      },
      {
        id: 14,
        field_id: 109,
        name: 'Νοτιοδυτικός',
      },
    ],
  },
  {
    id: 4169,
    type_id: 3,
    default_value: null,
    name: 'Πρόσβαση δύσκολη',
    types: [],
    field_options: [],
  },
  {
    id: 4168,
    type_id: 3,
    default_value: null,
    name: 'Πρόσβαση εύκολη',
    types: [],
    field_options: [],
  },
  {
    id: 4115,
    type_id: 3,
    default_value: null,
    name: 'Πρόσοψη',
    types: [],
    field_options: [],
  },
  {
    id: 100,
    type_id: 1,
    default_value: null,
    name: 'Πρόσοψη (μ.)',
    types: [2, 3, 11, 14, 17, 29],
    field_options: [],
  },
  {
    id: 4061,
    type_id: 3,
    default_value: null,
    name: 'Πρόσοψη σε άσφαλτο',
    types: [],
    field_options: [],
  },
  {
    id: 4089,
    type_id: 3,
    default_value: null,
    name: 'Πρόσοψη σε καλντερίμι',
    types: [],
    field_options: [],
  },
  {
    id: 4062,
    type_id: 3,
    default_value: null,
    name: 'Ράμπα',
    types: [],
    field_options: [],
  },
  {
    id: 4158,
    type_id: 3,
    default_value: null,
    name: 'Ράμπα αναπήρων',
    types: [],
    field_options: [],
  },
  {
    id: 4063,
    type_id: 3,
    default_value: null,
    name: 'Ρεσεψιόν',
    types: [],
    field_options: [],
  },
  {
    id: 4079,
    type_id: 3,
    default_value: null,
    name: 'Ρετιρέ',
    types: [],
    field_options: [],
  },
  {
    id: 4042,
    type_id: 3,
    default_value: null,
    name: 'Ρεύμα',
    types: [],
    field_options: [],
  },
  {
    id: 4166,
    type_id: 3,
    default_value: null,
    name: 'Ρεύμα αγροτικό',
    types: [],
    field_options: [],
  },
  {
    id: 4126,
    type_id: 3,
    default_value: null,
    name: 'Ρεύμα βιομηχανικό',
    types: [],
    field_options: [],
  },
  {
    id: 4117,
    type_id: 3,
    default_value: null,
    name: 'Ρεύμα νυχτερινό',
    types: [],
    field_options: [],
  },
  {
    id: 4068,
    type_id: 3,
    default_value: null,
    name: 'Ρεύμα τριφασικό',
    types: [],
    field_options: [],
  },
  {
    id: 4064,
    type_id: 3,
    default_value: null,
    name: 'Ρολόι ΔΕΗ',
    types: [],
    field_options: [],
  },
  {
    id: 4065,
    type_id: 3,
    default_value: null,
    name: 'Ρολόι νερού',
    types: [],
    field_options: [],
  },
  {
    id: 4100,
    type_id: 3,
    default_value: null,
    name: 'Σάουνα',
    types: [],
    field_options: [],
  },
  {
    id: 1203,
    type_id: 1,
    default_value: null,
    name: 'Σε οικόπεδο (τ.μ.)',
    types: [12],
    field_options: [],
  },
  {
    id: 4149,
    type_id: 3,
    default_value: null,
    name: 'Σίτες',
    types: [],
    field_options: [],
  },
  {
    id: 4097,
    type_id: 3,
    default_value: null,
    name: 'Σόμπα pellet',
    types: [],
    field_options: [],
  },
  {
    id: 4096,
    type_id: 3,
    default_value: null,
    name: 'Σόμπα πετρελαίου',
    types: [],
    field_options: [],
  },
  {
    id: 4133,
    type_id: 3,
    default_value: null,
    name: 'Σοφίτα',
    types: [],
    field_options: [],
  },
  {
    id: 4081,
    type_id: 3,
    default_value: null,
    name: 'Συναγερμός',
    types: [],
    field_options: [],
  },
  {
    id: 101,
    type_id: 1,
    default_value: null,
    name: 'Συντελεστής δόμησης',
    types: [2, 3, 29],
    field_options: [],
  },
  {
    id: 4088,
    type_id: 3,
    default_value: null,
    name: 'Τέντες',
    types: [],
    field_options: [],
  },
  {
    id: 2815,
    type_id: 1,
    default_value: null,
    name: 'Τεσσάρια (σύνολο)',
    types: [28],
    field_options: [],
  },
  {
    id: 4066,
    type_id: 3,
    default_value: null,
    name: 'Τζάκι',
    types: [],
    field_options: [],
  },
  {
    id: 4098,
    type_id: 3,
    default_value: null,
    name: 'Τζάκι ενεργειακό',
    types: [],
    field_options: [],
  },
  {
    id: 4122,
    type_id: 3,
    default_value: null,
    name: 'Τζακούζι',
    types: [],
    field_options: [],
  },
  {
    id: 1600,
    type_id: 1,
    default_value: null,
    name: 'Τιμή Πώλησης',
    types: [16],
    field_options: [],
  },
  {
    id: 2907,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. 1ος όροφος',
    types: [29],
    field_options: [],
  },
  {
    id: 1100,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. 1ου ορόφου',
    types: [11, 12, 14, 15, 17, 28, 31, 32, 33],
    field_options: [],
  },
  {
    id: 3024,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. 2ου ορόφου',
    types: [12, 28, 31, 32, 33],
    field_options: [],
  },
  {
    id: 3025,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. 3ου ορόφου',
    types: [12, 28, 31, 32, 33],
    field_options: [],
  },
  {
    id: 3026,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. 4ου ορόφου',
    types: [12, 28, 31, 32, 33],
    field_options: [],
  },
  {
    id: 3027,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. 5ου ορόφου',
    types: [12, 28, 31, 32, 33],
    field_options: [],
  },
  {
    id: 1002,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. ακινήτου (σύνολο)',
    types: [11, 12, 13, 14, 15, 16, 17, 29, 1000],
    field_options: [],
  },
  {
    id: 107,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. αποθήκης',
    types: [2, 3],
    field_options: [],
  },
  {
    id: 2818,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. αποθηκών (σύνολο)',
    types: [28],
    field_options: [],
  },
  {
    id: 2905,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. αυλής',
    types: [29],
    field_options: [],
  },
  {
    id: 1104,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. γραφείων (σύνολο)',
    types: [11, 17],
    field_options: [],
  },
  {
    id: 3202,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. διαμερισμάτων (σύνολο)',
    types: [32],
    field_options: [],
  },
  {
    id: 1003,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. εξωτ. χώρου',
    types: [11, 12, 13, 14, 15, 16, 17, 27, 28, 31, 32, 33, 1000],
    field_options: [],
  },
  {
    id: 3004,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. εστιατορίου',
    types: [31, 32, 33],
    field_options: [],
  },
  {
    id: 1004,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. ημιορόφου',
    types: [11, 12, 13, 14, 15, 16, 17, 28],
    field_options: [],
  },
  {
    id: 1006,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. Ημιυπαίθριου',
    types: [
      11, 12, 13, 14, 15, 16, 17, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32,
      33, 901, 1000,
    ],
    field_options: [],
  },
  {
    id: 200,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. θερμοκήπιο μεταλλικό',
    types: [2],
    field_options: [],
  },
  {
    id: 201,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. θερμοκήπιο ξύλινο',
    types: [2],
    field_options: [],
  },
  {
    id: 1005,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. ισογείου',
    types: [11, 12, 13, 14, 15, 16, 17, 28, 29, 31, 32, 33],
    field_options: [],
  },
  {
    id: 2804,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. καταστημάτων (σύνολο)',
    types: [28, 31, 32, 33],
    field_options: [],
  },
  {
    id: 106,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. κατοικίας',
    types: [2, 3],
    field_options: [],
  },
  {
    id: 102,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. κτίζει',
    types: [2, 3],
    field_options: [],
  },
  {
    id: 2811,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. κτιρίου (σύνολο)',
    types: [28, 31, 32, 33],
    field_options: [],
  },
  {
    id: 105,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. κτίσματος',
    types: [2, 3, 29, 1000],
    field_options: [],
  },
  {
    id: 1102,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. οικοπέδου',
    types: [11, 14, 15, 17, 28, 31, 32, 33, 1000],
    field_options: [],
  },
  {
    id: 1301,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. ορόφου',
    types: [13],
    field_options: [],
  },
  {
    id: 1007,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. ορόφων (σύνολο)',
    types: [11, 12, 13, 14, 15, 16, 17, 28, 31, 32, 33, 1000],
    field_options: [],
  },
  {
    id: 2908,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. πατάρι – οντάς',
    types: [29],
    field_options: [],
  },
  {
    id: 1008,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. παταριού',
    types: [11, 12, 13, 14, 15, 16, 17, 28],
    field_options: [],
  },
  {
    id: 2802,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. σπιτιών (σύνολο)',
    types: [28],
    field_options: [],
  },
  {
    id: 1009,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. υπογείου',
    types: [11, 12, 13, 14, 15, 16, 17, 26, 27, 28, 29, 31, 32, 33, 1000],
    field_options: [],
  },
  {
    id: 1105,
    type_id: 1,
    default_value: null,
    name: 'Τ.μ. ψυγείων (σύνολο)',
    types: [11, 17],
    field_options: [],
  },
  {
    id: 4067,
    type_id: 3,
    default_value: null,
    name: 'Τουαλέτα',
    types: [],
    field_options: [],
  },
  {
    id: 2814,
    type_id: 1,
    default_value: null,
    name: 'Τριάρια (σύνολο)',
    types: [28],
    field_options: [],
  },
  {
    id: 4188,
    type_id: 2,
    default_value: null,
    name: 'Τύπος parking',
    types: [902],
    field_options: [
      {
        id: 120,
        field_id: 4188,
        name: 'Parking πιλοτής',
      },
      {
        id: 121,
        field_id: 4188,
        name: 'Ανοιχτό parking',
      },
      {
        id: 122,
        field_id: 4188,
        name: 'Κλειστό parking',
      },
      {
        id: 123,
        field_id: 4188,
        name: 'Υπόγειο parking',
      },
    ],
  },
  {
    id: 4046,
    type_id: 3,
    default_value: null,
    name: 'Ύδρευση νερό',
    types: [],
    field_options: [],
  },
  {
    id: 2007,
    type_id: 1,
    default_value: null,
    name: 'Υπνοδωμάτια',
    types: [21, 22, 23, 24, 25, 26, 27, 28, 29, 1000],
    field_options: [],
  },
  {
    id: 4070,
    type_id: 3,
    default_value: null,
    name: 'Υπόγειο',
    types: [],
    field_options: [],
  },
  {
    id: 4069,
    type_id: 3,
    default_value: null,
    name: 'Υπό κατασκευή',
    types: [],
    field_options: [],
  },
  {
    id: 1103,
    type_id: 1,
    default_value: null,
    name: 'Ύψος (μ.)',
    types: [11, 12, 14, 15, 17],
    field_options: [],
  },
  {
    id: 4082,
    type_id: 3,
    default_value: null,
    name: 'Φυσικό αέριο',
    types: [],
    field_options: [],
  },
  {
    id: 4110,
    type_id: 3,
    default_value: null,
    name: 'Φωτεινό',
    types: [],
    field_options: [],
  },
  {
    id: 4099,
    type_id: 3,
    default_value: null,
    name: 'Φωτοβολταϊκό',
    types: [],
    field_options: [],
  },
  {
    id: 4113,
    type_id: 3,
    default_value: null,
    name: 'Χρήζει ανακαίνισης',
    types: [],
    field_options: [],
  },
  {
    id: 4152,
    type_id: 3,
    default_value: null,
    name: 'Χρηματοκιβώτιο',
    types: [],
    field_options: [],
  },
  {
    id: 4167,
    type_id: 3,
    default_value: null,
    name: 'Χρήση γής – ΣΧΟΑΠ',
    types: [],
    field_options: [],
  },
  {
    id: 4176,
    type_id: 3,
    default_value: null,
    name: 'Χρήση των γειτονικών',
    types: [],
    field_options: [],
  },
  {
    id: 4071,
    type_id: 3,
    default_value: null,
    name: 'Χρησιμοποιείται',
    types: [],
    field_options: [],
  },
  {
    id: 4150,
    type_id: 3,
    default_value: null,
    name: 'Χωρίς μεσιτική αμοιβή',
    types: [],
    field_options: [],
  },
  {
    id: 1010,
    type_id: 1,
    default_value: null,
    name: 'Χώροι',
    types: [11, 12, 13, 14, 15, 16, 17],
    field_options: [],
  },
  {
    id: 4072,
    type_id: 3,
    default_value: null,
    name: 'Χώρος υποδοχής',
    types: [],
    field_options: [],
  },
  {
    id: 4124,
    type_id: 3,
    default_value: null,
    name: 'Χώρος φορτοεκφόρτωσης',
    types: [],
    field_options: [],
  },
  {
    id: 4135,
    type_id: 3,
    default_value: null,
    name: 'Ψευδοροφή',
    types: [],
    field_options: [],
  },
  {
    id: 4156,
    type_id: 3,
    default_value: null,
    name: 'Ψυγείο',
    types: [],
    field_options: [],
  },
];

export const ESTATEWEB_INIT_PROPERTY_TYPES: EstateWebInitPropertyType[] = [
  {
    id: 20,
    name: 'Κατοικία',
    parent_id: null,
    children: [
      {
        id: 21,
        name: 'Γκαρσονιέρα',
        parent_id: 20,
        children: [],
      },
      {
        id: 22,
        name: 'Διαμέρισμα δυάρι',
        parent_id: 20,
        children: [],
      },
      {
        id: 23,
        name: 'Διαμέρισμα τριάρι',
        parent_id: 20,
        children: [],
      },
      {
        id: 24,
        name: 'Διαμέρισμα τεσσάρι',
        parent_id: 20,
        children: [],
      },
      {
        id: 25,
        name: 'Διαμέρισμα πεντάρι',
        parent_id: 20,
        children: [],
      },
      {
        id: 26,
        name: 'Μεζονέτα',
        parent_id: 20,
        children: [],
      },
      {
        id: 27,
        name: 'Μονοκατοικία',
        parent_id: 20,
        children: [],
      },
      {
        id: 28,
        name: 'Συγκρότημα - πολυκατοικία',
        parent_id: 20,
        children: [],
      },
      {
        id: 29,
        name: 'Παλαιά Κατοικία',
        parent_id: 20,
        children: [],
      },
      {
        id: 1000,
        name: 'Εξοχικό',
        parent_id: 20,
        children: [],
      },
    ],
  },
  {
    id: 10,
    name: 'Επαγγ. Χώρος',
    parent_id: null,
    children: [
      {
        id: 11,
        name: 'Αποθήκη',
        parent_id: 10,
        children: [],
      },
      {
        id: 12,
        name: 'Αυτοτελές κτίριο',
        parent_id: 10,
        children: [],
      },
      {
        id: 13,
        name: 'Γραφείο',
        parent_id: 10,
        children: [],
      },
      {
        id: 14,
        name: 'Κατάστημα',
        parent_id: 10,
        children: [],
      },
      {
        id: 15,
        name: 'Εργοστάσιο',
        parent_id: 10,
        children: [],
      },
      {
        id: 16,
        name: 'Επιχείρηση',
        parent_id: 10,
        children: [],
      },
      {
        id: 17,
        name: 'Βιοτεχνικό κτίριο',
        parent_id: 10,
        children: [],
      },
    ],
  },
  {
    id: 1,
    name: 'Έκταση',
    parent_id: null,
    children: [
      {
        id: 2,
        name: 'Αγροτεμάχιο',
        parent_id: 1,
        children: [],
      },
      {
        id: 3,
        name: 'Οικόπεδο',
        parent_id: 1,
        children: [],
      },
    ],
  },
  {
    id: 30,
    name: 'Κτίριο',
    parent_id: null,
    children: [
      {
        id: 31,
        name: 'Ξενοδοχείο',
        parent_id: 30,
        children: [],
      },
      {
        id: 32,
        name: 'Τουριστικό συγκρότημα',
        parent_id: 30,
        children: [],
      },
      {
        id: 33,
        name: 'Ενοικιαζόμενα δωμάτια',
        parent_id: 30,
        children: [],
      },
    ],
  },
  {
    id: 900,
    name: 'Λοιπά',
    parent_id: null,
    children: [
      {
        id: 902,
        name: 'Θέση στάθμευσης',
        parent_id: 900,
        children: [],
      },
      {
        id: 901,
        name: 'Άλλο',
        parent_id: 900,
        children: [],
      },
    ],
  },
];
