export interface EstateWebCrmClient {
  id: number;
  agent_id: number;
  group_id: number;
  user_id: number;
  last_name: string;
  first_name: string;
  father_name: string;
  email: string;
  phone_home: string;
  phone_work: string;
  phone_other: string;
  mobile: string;
  mobile_work: string;
  mobile_sms: string;
  fax: string;
  company_name: string;
  occupation: string;
  adt: string;
  vat_id: string;
  doy: string;
  address1: string;
  address2: string;
  zip: string;
  city: string;
  country: string;
  birthday: string | null;
  is_seller: boolean;
  is_buyer: boolean;
  is_lessor: boolean;
  is_lessee: boolean;
  is_final: boolean;
  is_interested: boolean;
  is_cooper: boolean;
  is_other: boolean;
  notes: string;
  created_by: number;
  updated_by: number;
  created_at: string;
  updated_at: string | null;
  deleted_at: string | null;
}
