export const ApiRoutes = {
    health: "/health",
    docs: {
        openapi: "/api",
        schema: "/api-json",
    },
    auth: {
        email: {
            login: "/auth/email/login",
            register: "/auth/email/register",
            refresh_token: "/auth/email/refresh-token",
            admin_login_to_account: (account_uuid: string) => `/auth/email/${account_uuid}/admin-login`,
            forgot_password: "/auth/email/forgot-password",
            reset_password: "/auth/email/reset-password",
            validate_reset_password: "/auth/email/reset-password/validate",
            send_user_password_reset: (userId: string) => `/auth/email/users/${userId}/password-reset`,
            verify_email: "/auth/verify-email",
            resend_verification_email: "/auth/resend-verification-email",
        },
    },
    users: {
        prefix: "/users",
        me: "/users/me",
        changePassword: "/users/me/change-password",
    },
    google_maps: {
        timezone: "/google-maps/timezone",
    },
    admin: {
        agencies: {
            prefix: "/admin/agencies",
            list: "/admin/agencies",
            detail: (id: string) => `/admin/agencies/${id}`,
            visibility: (id: string) => `/admin/agencies/${id}/visibility`,
            trackerSettings: (agencyId: string, userId: string) =>
                `/admin/agencies/${agencyId}/trackers/${userId}`,
        },
        scrapers: {
            prefix: "/admin/scrapers",
            list: "/admin/scrapers",
            detail: (id: string) => `/admin/scrapers/${id}`,
            versions: (id: string) => `/admin/scrapers/${id}/versions`,
            activateVersion: (id: string, versionId: string) =>
                `/admin/scrapers/${id}/versions/${versionId}/activate`,
            runNow: (id: string) => `/admin/scrapers/${id}/run-now`,
            bulkDelete: "/admin/scrapers/bulk-delete",
        },
        generationRuns: {
            prefix: "/admin/generation-runs",
            list: "/admin/generation-runs",
            detail: (id: string) => `/admin/generation-runs/${id}`,
            approve: (id: string) => `/admin/generation-runs/${id}/approve`,
            reject: (id: string) => `/admin/generation-runs/${id}/reject`,
            cancel: (id: string) => `/admin/generation-runs/${id}/cancel`,
            retry: (id: string) => `/admin/generation-runs/${id}/retry`,
            delete: (id: string) => `/admin/generation-runs/${id}`,
        },
        crawlRuns: {
            prefix: "/admin/crawl-runs",
            list: "/admin/crawl-runs",
            detail: (id: string) => `/admin/crawl-runs/${id}`,
            rerun: (id: string) => `/admin/crawl-runs/${id}/rerun`,
            cancel: (id: string) => `/admin/crawl-runs/${id}/cancel`,
            bulkDelete: "/admin/crawl-runs/bulk-delete",
        },
        cmsSyncRuns: {
            prefix: "/admin/cms-sync-runs",
            list: "/admin/cms-sync-runs",
            detail: (id: string) => `/admin/cms-sync-runs/${id}`,
            retry: (id: string) => `/admin/cms-sync-runs/${id}/retry`,
            rerun: (id: string) => `/admin/cms-sync-runs/${id}/rerun`,
            integrations: "/admin/cms-sync-runs/integrations",
            bulkDelete: "/admin/cms-sync-runs/bulk-delete",
        },
        jobs: {
            prefix: "/admin/jobs",
            list: "/admin/jobs",
            detail: (id: string) => `/admin/jobs/${id}`,
            retry: (id: string) => `/admin/jobs/${id}/retry`,
            stop: (id: string) => `/admin/jobs/${id}/stop`,
            bulkDelete: "/admin/jobs/bulk-delete",
        },
        queues: {
            bullBoard: "/admin/queues",
        },
        diagnostics: {
            prefix: "/admin/diagnostics",
            list: "/admin/diagnostics",
            detail: (id: string) => `/admin/diagnostics/${id}`,
        },
        properties: {
            prefix: "/admin/properties",
            list: "/admin/properties",
            count: "/admin/properties/count",
            detail: (id: string) => `/admin/properties/${id}`,
            merge: "/admin/properties/merge",
            bulkDelete: "/admin/properties/bulk-delete",
            dedupeGroups: "/admin/properties/dedupe-groups",
            truncateDescriptions: "/admin/properties/truncate-descriptions",
            bulkSplit: "/admin/properties/bulk-split",
            split: (id: string) => `/admin/properties/${id}/split`,
        },
        sourceProperties: {
            prefix: "/admin/source-properties",
            list: "/admin/source-properties",
            count: "/admin/source-properties/count",
            detail: (id: string) => `/admin/source-properties/${id}`,
            bulkDelete: "/admin/source-properties/bulk-delete",
        },
        userProperties: {
            prefix: "/admin/user-properties",
            list: "/admin/user-properties",
            count: "/admin/user-properties/count",
            detail: (id: string) => `/admin/user-properties/${id}`,
            migrateIntegrationImages: (id: string) =>
                `/admin/user-properties/${id}/migrate-integration-images`,
            deleteIntegrationImages: (id: string) =>
                `/admin/user-properties/${id}/delete-integration-images`,
            createIntegrationImages: (id: string) =>
                `/admin/user-properties/${id}/create-integration-images`,
            bulkDelete: "/admin/user-properties/bulk-delete",
            truncateDescriptions: "/admin/user-properties/truncate-descriptions",
            dedupeGroups: "/admin/user-properties/dedupe-groups",
            bulkSplit: "/admin/user-properties/bulk-split",
        },
        notifications: {
            prefix: "/admin/notifications",
            list: "/admin/notifications",
            detail: (id: string) => `/admin/notifications/${id}`,
            markRead: (id: string) => `/admin/notifications/${id}/read`,
            markAllRead: "/admin/notifications/read-all",
            bulkDelete: "/admin/notifications/bulk-delete",
            telegramTest: "/admin/notifications/telegram/test",
        },
        integrationTargets: {
            prefix: "/admin/integration-targets",
            list: "/admin/integration-targets",
            detail: (id: string) => `/admin/integration-targets/${id}`,
            visibility: (id: string) => `/admin/integration-targets/${id}/visibility`,
            accounts: (id: string) => `/admin/integration-targets/${id}/accounts`,
            account: (id: string, userIntegrationId: string) =>
                `/admin/integration-targets/${id}/accounts/${userIntegrationId}`,
            userSettings: (id: string, userId: string) =>
                `/admin/integration-targets/${id}/users/${userId}/settings`,
        },
        dashboard: {
            root: "/admin/dashboard",
        },
        platformConfig: {
            root: "/admin/platform-config",
        },
        users: {
            prefix: "/admin/users",
            list: "/admin/users",
            detail: (id: string) => `/admin/users/${id}`,
        },
    },
    integrations: {
        prefix: "/integrations",
        targets: "/integrations/targets",
        connections: "/integrations/connections",
        connection: (id: string) => `/integrations/connections/${id}`,
        connectionStatus: (id: string) => `/integrations/connections/${id}/status`,
        connectionDefault: (id: string) => `/integrations/connections/${id}/default`,
        settings: (targetId: string) => `/integrations/targets/${targetId}/settings`,
    },
    agencies: {
        prefix: "/agencies",
        list: "/agencies",
        track: (agencyId: string) => `/agencies/${agencyId}/track`,
        integrationLink: (agencyId: string) => `/agencies/${agencyId}/track/integration`,
    },
    cmsSyncRuns: {
        prefix: "/cms-sync-runs",
        list: "/cms-sync-runs",
        detail: (id: string) => `/cms-sync-runs/${id}`,
    },
    userProperties: {
        prefix: "/properties",
        list: "/properties",
        count: "/properties/count",
        detail: (id: string) => `/properties/${id}`,
        resync: (id: string) => `/properties/${id}/resync`,
        pushToCrm: (id: string) => `/properties/${id}/push-to-crm`,
        migrateIntegrationImages: (id: string) =>
            `/properties/${id}/migrate-integration-images`,
        deleteIntegrationImages: (id: string) =>
            `/properties/${id}/delete-integration-images`,
        createIntegrationImages: (id: string) =>
            `/properties/${id}/create-integration-images`,
        bulkPushToCrm: "/properties/push-to-crm",
        bulkDelete: "/properties/bulk-delete",
        dedupeGroups: "/properties/dedupe-groups",
        bulkSplit: "/properties/bulk-split",
        truncateDescriptions: "/properties/truncate-descriptions",
    },
    estateweb: {
        catalog: {
            locations: "/estateweb/catalog/locations",
            floors: "/estateweb/catalog/floors",
            energyClasses: "/estateweb/catalog/energy-classes",
            roadTypes: "/estateweb/catalog/road-types",
            listingTypes: "/estateweb/catalog/listing-types",
            propertyTypes: "/estateweb/catalog/property-types",
            features: "/estateweb/catalog/features",
        },
    },
    dashboard: {
        root: "/dashboard",
    },
}