import { Page } from 'playwright';

export async function isAccessBlockedPage(page: Page): Promise<boolean> {
  return page
    .evaluate(() => {
      const text = document.body?.innerText ?? '';
      const title = document.title ?? '';
      const html = document.documentElement?.innerHTML?.slice(0, 4000) ?? '';

      return (
        title.includes('ERROR: The request could not be satisfied') ||
        text.includes('Request blocked') ||
        text.includes('403 ERROR') ||
        /Generated by cloudfront \(CloudFront\)/i.test(text) ||
        /Access Denied/i.test(title) ||
        (/cf-error-details|CloudFront/i.test(html) &&
          /403|blocked|denied/i.test(text))
      );
    })
    .catch(() => false);
}
